{% set name = "tectonic" %}
{% set version = "0.15.0" %}
{% set sha256 = "3c13de312c4fe39ff905ad17e64a15a3a59d33ab65dacb0a8b9482c57e6bc6aa" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/tectonic-typesetting/{{ name }}/archive/refs/tags/{{ name }}@{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - pr-1202-fix-use-cxx-17.patch
    - winzip.patch  # [win]

build:
  number: 3

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ posix }}patch         # [win]
    - {{ native }}pkg-config
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
    - glib       # [build_platform != target_platform]
    - harfbuzz   # [build_platform != target_platform]

  host:
    - expat  # [not osx]
    - fontconfig  # [not osx]
    - freetype
    - glib  # development files needed by harfbuzz
    - graphite2
    - harfbuzz
    - icu
    - libpng
    - openssl
    - zlib

  run:
    - fontconfig  # [not osx]
    - freetype
    - graphite2
    - harfbuzz
    - icu
    - libpng
    - openssl
    - zlib

test:
  files:
    - example.tex
  commands:
    - tectonic --help
    - tectonic example.tex

about:
  home: https://tectonic-typesetting.github.io/
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A modernized, complete, standalone TeX/LaTeX engine.
  doc_url: https://tectonic-typesetting.github.io/book/latest/
  dev_url: https://github.com/tectonic-typesetting/tectonic/

extra:
  recipe-maintainers:
    - pkgw
    - anjos
