{% set name = "tectonic" %}
{% set version = "0.1.9" %}
{% set sha256 = "48ae8ef5e733ea2cc0cd742013c9832403f73acb39327ff06ec746056f5a501c" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://crates.io/api/v1/crates/{{ name }}/{{ version }}/download
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - rust
    - {{native}}pkg-config
    - {{ compiler('c') }}    # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - vs2015_win-64          # [win] -- VS2008 too annoying to support

  host:
    - fontconfig  # [not osx]
    - freetype
    - graphite2
    - harfbuzz
    - icu
    - libpng >=1.6.35  # [win] -- needed for some reason to get a package new enough to have a pkg-config file
    - openssl
    - zlib

  run:
    - fontconfig  # [not osx]
    - freetype
    - graphite2
    - harfbuzz
    - icu
    - libpng
    - openssl
    - zlib

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - tectonic --help

about:
  home: https://tectonic-typesetting.github.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A modernized, complete, standalone TeX/LaTeX engine.'
  doc_url: https://tectonic-typesetting.github.io/en-US/learn.html
  dev_url: https://github.com/tectonic-typesetting/tectonic/

extra:
  recipe-maintainers:
    - pkgw
