{% set name = "tectonic" %}
{% set version = "0.1.14" %}
{% set sha256 = "5e940ba1fae829c617b6c9c2098f218a62abffdf1c98d13e363ff2ed0897ca10" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://crates.io/api/v1/crates/{{ name }}/{{ version }}/download
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - rust
    - {{ posix }}patch         # [win]
    - {{ native }}pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - fontconfig  # [not osx]
    - freetype
    - graphite2
    - harfbuzz
    - icu
    - libpng
    - openssl
    - zlib

  run:
    - fontconfig  # [not osx]
    - freetype
    - graphite2
    - harfbuzz
    - icu
    - libpng
    - openssl
    - zlib

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - tectonic --help

about:
  home: https://tectonic-typesetting.github.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A modernized, complete, standalone TeX/LaTeX engine.
  doc_url: https://tectonic-typesetting.github.io/learn.html
  dev_url: https://github.com/tectonic-typesetting/tectonic/

extra:
  recipe-maintainers:
    - pkgw
