{% set name = "tectonic" %}
{% set version = "0.5.2" %}
{% set sha256 = "cd9b69627335c696a7e3abf8319d9fd2f2bb44c7b8e1f92d2ad7e8e1a82e0d14" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://crates.io/api/v1/crates/{{ name }}/{{ version }}/download
  sha256: {{ sha256 }}
  patches:
    - winzip.patch  # [win]

build:
  number: 0

requirements:
  build:
    - rust
    - {{ posix }}patch         # [win]
    - {{ native }}pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - fontconfig  # [not osx]
    - freetype
    - glib  # development files needed by harfbuzz
    - graphite2
    - harfbuzz
    - icu
    - libpng
    - openssl
    - zlib

  run:
    - fontconfig  # [not osx]
    - freetype
    - graphite2
    - harfbuzz
    - icu
    - libpng
    - openssl
    - zlib

test:
  files:
    - example.tex
  commands:
    - tectonic --help
    - tectonic example.tex

about:
  home: https://tectonic-typesetting.github.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A modernized, complete, standalone TeX/LaTeX engine.
  doc_url: https://tectonic-typesetting.github.io/learn.html
  dev_url: https://github.com/tectonic-typesetting/tectonic/

extra:
  recipe-maintainers:
    - pkgw
