{% set name = "tectonic" %}
{% set version = "0.12.0" %}
{% set sha256 = "ec7e4c19f5e618889cdedf8d30b3146210987068efd33f46bfde3d3198f895e0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://crates.io/api/v1/crates/{{ name }}/{{ version }}/download
  sha256: {{ sha256 }}
  patches:
    - winzip.patch  # [win]

build:
  number: 3

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ posix }}patch         # [win]
    - {{ native }}pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
    - glib       # [build_platform != target_platform]
    - harfbuzz   # [build_platform != target_platform]

  host:
    - fontconfig  # [not osx]
    - freetype
    - glib  # development files needed by harfbuzz
    - graphite2
    - harfbuzz
    - icu
    - libpng
    - openssl
    - zlib

  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    - fontconfig  # [not osx]
    - freetype
    - graphite2
    - harfbuzz
    - icu
    - libpng
    - openssl
    - zlib

test:
  files:
    - example.tex
  commands:
    - tectonic --help
    - tectonic example.tex

about:
  home: https://tectonic-typesetting.github.io/
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A modernized, complete, standalone TeX/LaTeX engine.
  doc_url: https://tectonic-typesetting.github.io/book/latest/
  dev_url: https://github.com/tectonic-typesetting/tectonic/

extra:
  recipe-maintainers:
    - pkgw
